CREATE TABLE pokemons (
    name VARCHAR(50) not NULL,
    type1 VARCHAR(50),
    type2 VARCHAR(50),
    image_url VARCHAR(255),
    UNIQUE(name)
);

INSERT INTO pokemons (name, type1, type2, image_url) VALUES
('Abo', 'Poison', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/23/regular.png'),
('Arcko', 'Plante', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/252/regular.png'),
('Artikodin', 'Glace', 'Vol', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/144/regular.png'),
('Axoloto', 'Eau', 'Sol', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/194/regular.png'),
('Azumarill', 'Eau', 'Fée', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/184/regular.png'),
('Azurill', 'Normal', 'Fée', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/298/regular.png'),
('Balignon', 'Plante', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/315/regular.png'),
('Blizzaroi', 'Plante', 'Glace', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/460/regular.png'),
('Bulbizarre', 'Plante', 'Poison', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/1/regular.png'),
('Carapuce', 'Eau', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/7/regular.png'),
('Coconfort', 'Insecte', 'Poison', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/14/regular.png'),
('Dialga', 'Acier', 'Dragon', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/483/regular.png'),
('Dracaufeu', 'Feu', 'Vol', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/6/regular.png'),
('Drattak', 'Dragon', 'Vol', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/149/regular.png'),
('Ectoplasma', 'Spectre', 'Poison', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/94/regular.png'),
('Florizarre', 'Plante', 'Poison', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/3/regular.png'),
('Galopa', 'Feu', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/78/regular.png'),
('Goupix', 'Feu', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/37/regular.png'),
('Kyogre', 'Eau', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/382/regular.png'),
('Lucario', 'Combat', 'Acier', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/448/regular.png'),
('Lugia', 'Psy', 'Vol', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/249/regular.png'),
('Léviator', 'Eau', 'Vol', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/130/regular.png'),
('Magicarpe', 'Eau', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/129/regular.png'),
('Mewtwo', 'Psy', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/150/regular.png'),
('Mimiqui', 'Spectre', 'Fée', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/778/regular.png'),
('Nidoking', 'Poison', 'Sol', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/34/regular.png'),
('Noctali', 'Ténèbres', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/197/regular.png'),
('Piafabec', 'Normal', 'Vol', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/21/regular.png'),
('Pichu', 'Électrik', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/172/regular.png'),
('Pikachu', 'Électrik', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/25/regular.png'),
('Raichu', 'Électrik', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/26/regular.png'),
('Rattata', 'Normal', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/19/regular.png'),
('Rayquaza', 'Dragon', 'Vol', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/384/regular.png'),
('Ronflex', 'Normal', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/143/regular.png'),
('Sabelette', 'Sol', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/27/regular.png'),
('Salamèche', 'Feu', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/4/regular.png'),
('Simiabraz', 'Feu', 'Combat', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/392/regular.png'),
('Soporifik', 'Psy', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/96/regular.png'),
('Spiritomb', 'Spectre', 'Ténèbres', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/442/regular.png'),
('Sulfura', 'Feu', 'Vol', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/146/regular.png'),
('Tortank', 'Eau', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/9/regular.png'),
('Torterra', 'Plante', 'Sol', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/389/regular.png'),
('Tortipouss', 'Plante', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/387/regular.png'),
('Tyranocif', 'Roche', 'Ténèbres', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/248/regular.png'),
('Vipélierre', 'Plante', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/495/regular.png'),
('Zygarde', 'Dragon', 'Sol', 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/718/regular.png'),
('Évoli', 'Normal', NULL, 'https://raw.githubusercontent.com/Yarkis01/TyraDex/images/sprites/133/regular.png');
